// Writes tokens.json, tokens.js and tokens.d.ts from Terrazzo's resolved values (dist/terrazzo.js), then
// removes that intermediate file. Each theme maps a token id to its resolved CSS value, so scripts can
// read the tokens without depending on Terrazzo's types (design-system#2, DS-D2's fallback).
import { rm, writeFile } from "node:fs/promises";

const { PERMUTATIONS } = await import(new URL("../dist/terrazzo.js", import.meta.url));

const px = (d) => `${d.value}${d.unit}`;
const color = (c) =>
  (c.alpha ?? 1) === 1
    ? c.hex
    : `rgb(${c.components.map((x) => Math.round(x * 255)).join(" ")} / ${c.alpha})`;
const cssValue = (token) => {
  const v = token.$value;
  switch (token.$type) {
    case "color":
      return color(v);
    case "dimension":
      return px(v);
    case "fontFamily":
      return v.map((f) => (/^[\w-]+$/.test(f) ? f : `"${f}"`)).join(", ");
    case "fontWeight":
    case "number":
      return v;
    case "shadow":
      return (Array.isArray(v) ? v : [v])
        .map((s) => [px(s.offsetX), px(s.offsetY), px(s.blur), px(s.spread), color(s.color)].join(" "))
        .join(", ");
    default:
      throw new Error(`no CSS value for $type ${token.$type} (${token.id})`);
  }
};

const themes = {};
for (const [input, set] of Object.entries(PERMUTATIONS)) {
  const { theme } = JSON.parse(input);
  themes[theme] = Object.fromEntries(
    Object.entries(set)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([id, token]) => [id, cssValue({ ...token, id })]),
  );
}

const header = "// Generated by scripts/emit.mjs from the token sources. Do not edit.\n";
const ids = Object.keys(themes.light);
await writeFile(new URL("../dist/tokens.json", import.meta.url), `${JSON.stringify(themes, null, 2)}\n`);
await writeFile(
  new URL("../dist/tokens.js", import.meta.url),
  `${header}export const tokens = ${JSON.stringify(themes, null, 2)};\nexport default tokens;\n`,
);
await writeFile(
  new URL("../dist/tokens.d.ts", import.meta.url),
  `${header}export type Theme = ${Object.keys(themes)
    .map((t) => JSON.stringify(t))
    .join(" | ")};\nexport type TokenId =\n${ids.map((id) => `  | ${JSON.stringify(id)}`).join("\n")};\n` +
    `/** Resolved CSS values by theme and token id; in CSS use var(--ds-<id with dots as hyphens>). */\n` +
    `export declare const tokens: Readonly<Record<Theme, Readonly<Record<TokenId, string | number>>>>;\nexport default tokens;\n`,
);
await rm(new URL("../dist/terrazzo.js", import.meta.url));
await rm(new URL("../dist/terrazzo.d.ts", import.meta.url), { force: true });
